site_name: metpipe
theme:
    name: material
    custom_dir: overrides
    features:
        - navigation.tabs
        - navigation.footer
    icon:
        repo: fontawesome/brands/github
        logo: material/forest-outline #material/library-outline
    favicon: material/library-shelves
    

nav:
  - Home: 'index.md'
  - Workflow: 
    - workflow/introduction.md 
    - Study design & data organization:
      - Introduction: workflow/design_intro.md
      - Randomization: workflow/design_randomization.md
      - Quality control setup: workflow/design_qc_setup.md
      - Data conversion: workflow/design_data_conversion.md
      - LC-MS data structure: workflow/design_data_structure.md 
    - Untargeted data processing:
      - Introduction: workflow/untar_intro.md
      - Preprocessing: workflow/untar_preprocessing.md
      - Identification:
        - General: workflow/untar_identification.md
        - Lipid annotation: workflow/untar_identification_lip.md
      - Quality control: workflow/untar_qc.md
      - Post processing:
        - Peak cleaning: workflow/untar_clean.md
        - Missing imputation: workflow/untar_missing_imputation.md
        - Normalization: workflow/untar_normalization.md
        - Merge peaklist: workflow/untar_merge.md
    # - Targeted data processing:
    #   - Introduction: workflow/tar_intro.md
    #   - Targets and assay design: workflow/tar_targets.md
    #   - Standards and internal standards: workflow/tar_standards.md
    #   - Calibration: workflow/calibration.md
    #   - Batch design and QC: workflow/tar_batch_qc.md
    #   - Acquisition (MRM/PRM): workflow/tar_acquisition.md
    #   - Data processing: workflow/tar_processing.md
    #   - Acceptance criteria: workflow/tar_acceptance.md
    #   - Reporting: workflow/tar_reporting.md
    # - Statistical analysis and interpretation:
    #   - Introduction: workflow/stat_intro.md
    #   - Univariate analysis: workflow/univariate.md
    #   - Multivariate analysis: workflow/multivariate.md
    #   - Pathway analysis: workflow/pathway.md
    # - Other topics:
    #   - Retention time prediction: workflow/untar_rt_prediction.md

  - metpipe:
    - metpipe/introduction.md 
    - Set up input folder: metpipe/setup_input_folder.md
    - Untargeted processing pipeline: metpipe/pipeline.md

    #   - Preprocessing: 
    #   - Targeted peak picking: metpipe/tar.md
    #   - Untargeted peak picking: 
    #     - XCMS: metpipe/untar_xcms.md
    #     - MS-DIAL: metpipe/untar_msdial.md
    #     - MZmine: metpipe/untar_mzmine.md
    #   - Targeted untargeted preprocessing: metpipe/tar_untar.md
    # - Peak cleaning: metpipe/clean.md
    # - Normalization: metpipe/normalization.md
    # - Merge peaklist: metpipe/merge.md
    # - Generate QC report: metpipe/qc_report.md

  - Data explorer:
    - Introduction: data_explorer/introduction.md
    - Randomization: data_explorer/randomization.md 
    - Generate sample list: data_explorer/generate_sample_list.md 
    - Match library: data_explorer/match_library.md
    - Retention time mapping: data_explorer/rt_mapping.md
    - Calibration: data_explorer/calibration.md
    - Upload peaklist: data_explorer/upload.md
    - Preprocessing: data_explorer/preprocessing.md


extra_css:
  - css/extra.css

extra:
  generator: false

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Repository
repo_url: https://github.com/qian-gao/metpipe_docss
repo_name: qian-gao/metpipe
#repo_counts: true

