site_name: metpipe
theme:
    name: material
    custom_dir: overrides
    features:
        - navigation.tabs
        - navigation.footer
    icon:
        repo: fontawesome/brands/github
        logo: material/forest-outline #material/library-outline
    favicon: material/library-shelves
    

nav:
  - Home: 'index.md'
  - Workflow: 
    - workflow/introduction.md 
    - General guidelines:
      - Randomization: workflow/randomization.md
      - QC samples steup: workflow/qc_setup.md
      - Data conversion: workflow/data_conversion.md
      - LC-MS data structure: workflow/data_structure.md 
    - Untargeted data processing:
      - Quality control: workflow/qc_is.md
      - Retention time prediction: workflow/rt_prediction.md
      - Preprocessing: workflow/preprocessing.md
      - Peak grouping: workflow/peak_grouping.md
      - Peak cleaning: workflow/clean.md
      - Missing imputation: workflow/missing_imputation.md
      - Normalization: workflow/normalization.md
      - Merge peaklist: workflow/merge.md
    - Targeted data processing:
      - Quantification: workflow/quantification.md

  - metpipe:
    - metpipe/introduction.md 
    - Set up input folder: metpipe/setup_input_folder.md
    - Untargeted processing pipeline: metpipe/pipeline.md

    #   - Preprocessing: 
    #   - Targeted peak picking: metpipe/tar.md
    #   - Untargeted peak picking: 
    #     - XCMS: metpipe/untar_xcms.md
    #     - MS-DIAL: metpipe/untar_msdial.md
    #     - MZmine: metpipe/untar_mzmine.md
    #   - Targeted untargeted preprocessing: metpipe/tar_untar.md
    # - Peak cleaning: metpipe/clean.md
    # - Normalization: metpipe/normalization.md
    # - Merge peaklist: metpipe/merge.md
    # - Generate QC report: metpipe/qc_report.md

  - Data explorer:
    - Introduction: data_explorer/introduction.md
    - Randomization: data_explorer/randomization.md 
    - Generate sample list: data_explorer/generate_sample_list.md 
    - Match library: data_explorer/match_library.md
    - Retention time mapping: data_explorer/rt_mapping.md
    - Calibration: data_explorer/calibration.md
    - Upload peaklist: data_explorer/upload.md
    - Preprocessing: data_explorer/preprocessing.md


extra_css:
  - css/extra.css

extra:
  generator: false

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Repository
repo_url: https://github.com/qian-gao/metpipe_docss
repo_name: qian-gao/metpipe
#repo_counts: true

